### ISSUE TITLE
Fix restarting websockets daily

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/FinTwit_Bot#136]
Maybe test by force closing the websocket and restarting it

**Comment by StephanAkkerman** [comment]
KuCoin ws are working!

**Comment by StephanAkkerman** [comment]
Issue with Binance sockets:
Task exception was never retrieved
future: <Task finished name='Task-47' coro=<KuCoin.start_sockets() done, defined at /home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py:397> exception=RuntimeError('cannot call recv while another coroutine is already waiting for the next message')>
Traceback (most recent call last):
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 474, in start_sockets
    reply = await self.ws.recv()
  File "/home/pi/venv38/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/pi/venv38/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: sent 1000 (OK); then received 1000 (OK)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 479, in start_sockets
    await self.restart_sockets()
  File "/home/pi/venv38/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 181, in __call__
    return await self.coro(*args, **kwargs)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 387, in restart_sockets
    await self.start_sockets()
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 479, in start_sockets
    await self.restart_sockets()
  File "/home/pi/venv38/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 181, in __call__
    return await self.coro(*args, **kwargs)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 387, in restart_sockets
    await self.start_sockets()
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 479, in start_sockets
    await self.restart_sockets()
  File "/home/pi/venv38/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 181, in __call__
    return await self.coro(*args, **kwargs)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 387, in restart_sockets
    await self.start_sockets()
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 474, in start_sockets
    reply = await self.ws.recv()
  File "/home/pi/venv38/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 516, in recv
    raise RuntimeError(
RuntimeError: cannot call recv while another coroutine is already waiting for the next message

**Comment by StephanAkkerman** [comment]
Added return to fix issue above

**Comment by StephanAkkerman** [comment]
Now just ignores the runtime error
