### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/FinTwit_Bot#143]

**Comment by StephanAkkerman** [comment]
Unhandled exception in internal background task 'get_following_ids'.
Traceback (most recent call last):
  File "/home/pi/venv38/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/timeline.py", line 113, in get_following_ids
    self.following_ids = api.get_friend_ids()
  File "/home/pi/venv38/lib/python3.8/site-packages/tweepy/api.py", line 33, in wrapper
    return method(*args, **kwargs)
  File "/home/pi/venv38/lib/python3.8/site-packages/tweepy/api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "/home/pi/venv38/lib/python3.8/site-packages/tweepy/api.py", line 2131, in get_friend_ids
    return self.request(
  File "/home/pi/venv38/lib/python3.8/site-packages/tweepy/api.py", line 263, in request
    raise TooManyRequests(resp)
tweepy.errors.TooManyRequests: 429 Too Many Requests
88 - Rate limit exceeded

**Comment by StephanAkkerman** [comment]
future: <Task finished name='Task-35' coro=<KuCoin.start_sockets() done, defined at /home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py:323> exception=KeyError('matchPrice')>
Traceback (most recent call last):
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 374, in start_sockets
    await self.on_msg(reply)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 293, in on_msg
    execPrice = data['matchPrice']
KeyError: 'matchPrice'

**Comment by StephanAkkerman** [comment]
KuCoin: Connection Closed
Task exception was never retrieved
future: <Task finished name='Task-35' coro=<KuCoin.start_sockets() done, defined at /home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py:323> exception=ClientConnectorError(ConnectionKey(host='api.kucoin.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(-3, 'Temporary failure in name resolution'))>
Traceback (most recent call last):
  File "/home/pi/venv38/lib/python3.8/site-packages/aiohttp/connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/pi/venv38/lib/python3.8/site-packages/aiohttp/connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/pi/venv38/lib/python3.8/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 378, in start_sockets
    await self.restart_sockets()
  File "/home/pi/venv38/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 181, in __call__
    return await self.coro(*args, **kwargs)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 321, in restart_sockets
    await self.start_sockets()
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 349, in start_sockets
    async with session.post(
  File "/home/pi/venv38/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/pi/venv38/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/home/pi/venv38/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/pi/venv38/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/pi/venv38/lib/python3.8/site-packages/aiohttp/connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.kucoin.com:443 ssl:default [Temporary failure in name resolution]

**Comment by StephanAkkerman** [comment]
Unhandled exception in internal background task 'crypto'.
Traceback (most recent call last):
  File "/home/pi/venv38/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/gainers.py", line 58, in crypto
    e_losers = await format_embed(losers, 'Losers', 'binance')
  File "/home/pi/FinTwit_Bot/src/util/formatting.py", line 58, in format_embed
    df['Volume'] = df['Volume'].apply(lambda x: "$" + human_format(x))
  File "/home/pi/venv38/lib/python3.8/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/home/pi/venv38/lib/python3.8/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/home/pi/venv38/lib/python3.8/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/home/pi/FinTwit_Bot/src/util/formatting.py", line 58, in <lambda>
    df['Volume'] = df['Volume'].apply(lambda x: "$" + human_format(x))
  File "/home/pi/FinTwit_Bot/src/util/formatting.py", line 16, in human_format
    magnitude = int(floor(log(number, k)))
ValueError: math domain error

**Comment by StephanAkkerman** [comment]
Unhandled exception in internal background task 'wsb'.
Traceback (most recent call last):
  File "/home/pi/venv38/lib/python3.8/site-packages/asyncprawcore/requestor.py", line 64, in request
    return await self._http.request(
  File "/home/pi/venv38/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/home/pi/venv38/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/home/pi/venv38/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/venv38/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/reddit.py", line 52, in wsb
    async for submission in subreddit.hot(limit=10):
  File "/home/pi/venv38/lib/python3.8/site-packages/asyncpraw/models/listing/generator.py", line 63, in __anext__
    await self._next_batch()
  File "/home/pi/venv38/lib/python3.8/site-packages/asyncpraw/models/listing/generator.py", line 73, in _next_batch
    self._listing = await self._reddit.get(self.url, params=self.params)
  File "/home/pi/venv38/lib/python3.8/site-packages/asyncpraw/reddit.py", line 661, in get
    return await self._objectify_request(method="GET", params=params, path=path)
  File "/home/pi/venv38/lib/python3.8/site-packages/asyncpraw/reddit.py", line 765, in _objectify_request
    await self.request(
  File "/home/pi/venv38/lib/python3.8/site-packages/asyncpraw/reddit.py", line 967, in request
    return await self._core.request(
  File "/home/pi/venv38/lib/python3.8/site-packages/asyncprawcore/sessions.py", line 370, in request
    return await self._request_with_retries(
  File "/home/pi/venv38/lib/python3.8/site-packages/asyncprawcore/sessions.py", line 270, in _request_with_retries
    response, saved_exception = await self._make_request(
  File "/home/pi/venv38/lib/python3.8/site-packages/asyncprawcore/sessions.py", line 187, in _make_request
    response = await self._rate_limiter.call(
  File "/home/pi/venv38/lib/python3.8/site-packages/asyncprawcore/rate_limit.py", line 35, in call
    response = await request_function(*args, **kwargs)
  File "/home/pi/venv38/lib/python3.8/site-packages/asyncprawcore/requestor.py", line 68, in request
    raise RequestException(exc, args, kwargs)
asyncprawcore.exceptions.RequestException: error with request

**Comment by StephanAkkerman** [comment]
Task exception was never retrieved
future: <Task finished name='Task-35' coro=<Loop._loop() done, defined at /home/pi/venv38/lib/python3.8/site-packages/discord/ext/tasks/__init__.py:88> exception=RuntimeError('cannot call recv while another coroutine is already waiting for the next message')>
Traceback (most recent call last):
  File "/home/pi/venv38/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 125, in _loop
    raise exc
  File "/home/pi/venv38/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 386, in restart_sockets
    await self.start_sockets()
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 465, in start_sockets
    reply = await self.ws.recv()
  File "/home/pi/venv38/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 516, in recv
    raise RuntimeError(
RuntimeError: cannot call recv while another coroutine is already waiting for the next message

**Comment by StephanAkkerman** [comment]
future: <Task finished name='Task-36' coro=<KuCoin.start_sockets() done, defined at /home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py:388> exception=KeyError('matchPrice')>
Traceback (most recent call last):
  File "/home/pi/venv38/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 944, in transfer_data
    message = await self.read_message()
  File "/home/pi/venv38/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1013, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/pi/venv38/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1089, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/pi/venv38/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1144, in read_frame
    frame = await Frame.read(
  File "/home/pi/venv38/lib/python3.8/site-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 465, in start_sockets
    reply = await self.ws.recv()
  File "/home/pi/venv38/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/pi/venv38/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 920, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 470, in start_sockets
    await self.restart_sockets()
  File "/home/pi/venv38/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 181, in __call__
    return await self.coro(*args, **kwargs)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 386, in restart_sockets
    await self.start_sockets()
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 470, in start_sockets
    await self.restart_sockets()
  File "/home/pi/venv38/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 181, in __call__
    return await self.coro(*args, **kwargs)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 386, in restart_sockets
    await self.start_sockets()
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 470, in start_sockets
    await self.restart_sockets()
  File "/home/pi/venv38/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 181, in __call__
    return await self.coro(*args, **kwargs)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 386, in restart_sockets
    await self.start_sockets()
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 466, in start_sockets
    await self.on_msg(reply)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 342, in on_msg
    execPrice = data["matchPrice"]
KeyError: 'matchPrice'
