### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/FinTwit_Bot#157]
Traceback (most recent call last):
  File "/home/pi/venv38/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 401, in restart_sockets
    await self.start_sockets()
  File "/home/pi/FinTwit_Bot/src/cogs/loops/exchange_data.py", line 488, in start_sockets
    reply = await self.ws.recv()
  File "/home/pi/venv38/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 516, in recv
    raise RuntimeError(
RuntimeError: cannot call recv while another coroutine is already waiting for the next message

**Comment by StephanAkkerman** [comment]
Traceback (most recent call last):
  File "/home/pi/venv38/lib/python3.8/site-packages/pycoingecko/api.py", line 29, in __request
    response.raise_for_status()
  File "/home/pi/venv38/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.coingecko.com/api/v3/coins/hoodler/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/FinTwit_Bot/src/util/tweet_util.py", line 197, in add_financials
    volume, website, exchanges, price, change, ta = classify_ticker(
  File "/home/pi/FinTwit_Bot/src/util/ticker.py", line 191, in classify_ticker
    coin = get_coin_info(ticker)
  File "/home/pi/FinTwit_Bot/src/util/ticker.py", line 43, in get_coin_info
    coin_dict = cg.get_coin_by_id(id)
  File "/home/pi/venv38/lib/python3.8/site-packages/pycoingecko/utils.py", line 12, in input_args
    return func(*args, **kwargs)
  File "/home/pi/venv38/lib/python3.8/site-packages/pycoingecko/api.py", line 140, in get_coin_by_id
    return self.__request(api_url)
  File "/home/pi/venv38/lib/python3.8/site-packages/pycoingecko/api.py", line 36, in __request
    raise ValueError(content)
ValueError: {'error': 'Could not find coin with the given id'}

**Comment by StephanAkkerman** [comment]
Traceback (most recent call last):
  File "/home/pi/venv38/lib/python3.8/site-packages/tweepy/asynchronous/streaming.py", line 112, in _connect
    await self.on_data(line)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/timeline.py", line 131, in on_data
    await self.post_tweet(*formatted_tweet)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/timeline.py", line 169, in post_tweet
    msg, channel = await self.upload_tweet(
  File "/home/pi/FinTwit_Bot/src/cogs/loops/timeline.py", line 221, in upload_tweet
    msg = await channel.send(embed=e)
  File "/home/pi/venv38/lib/python3.8/site-packages/discord/abc.py", line 1065, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/home/pi/venv38/lib/python3.8/site-packages/discord/http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 504 Gateway Time-out (error code: 0): <!DOCTYPE html>

**Comment by StephanAkkerman** [comment]
Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/friends/ids.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xa3076e50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Failed to get following ids
Exception in thread Thread-67:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
TypeError: 'str' object is not callable
Exception in thread Thread-68:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
TypeError: 'str' object is not callable

**Comment by StephanAkkerman** [comment]
Traceback (most recent call last):
  File "/home/pi/venv38/lib/python3.8/site-packages/tweepy/asynchronous/streaming.py", line 112, in _connect
    await self.on_data(line)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/timeline.py", line 131, in on_data
    await self.post_tweet(*formatted_tweet)
  File "/home/pi/FinTwit_Bot/src/cogs/loops/timeline.py", line 154, in post_tweet
    e, category = await add_financials(
  File "/home/pi/FinTwit_Bot/src/util/tweet_util.py", line 243, in add_financials
    if "Binance" in exchanges:
TypeError: argument of type 'NoneType' is not iterable
