### ISSUE TITLE
Fix /analyze

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/FinTwit_Bot#302]
Traceback (most recent call last):
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 198, in _loop
    raise exc
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 169, in _loop
    await self.coro(*args, **kwargs)
  File "/home/akkie100/FinTwit_Bot/src/cogs/loops/nfts.py", line 174, in top_p2e
    p2e = await p2e_games()
  File "/home/akkie100/FinTwit_Bot/src/cogs/loops/nfts.py", line 342, in p2e_games
    allItems = items.find_all('tr')
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by StephanAkkerman** [comment]
Traceback (most recent call last):
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/commands/core.py", line 970, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "/home/akkie100/FinTwit_Bot/src/cogs/commands/analyze.py", line 53, in analyze
    table = table_div.find("table")
AttributeError: 'NoneType' object has no attribute 'find'
