### ISSUE TITLE
get tweet keyerror

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/FinTwit_Bot#365]
Unhandled exception in internal background task 'get_latest_tweet'.
Traceback (most recent call last):
  File "C:\Users\super\Anaconda3\envs\discord\lib\site-packages\discord\ext\tasks\__init__.py", line 169, in _loop
    await self.coro(*args, **kwargs)
  File "C:\Users\super\OneDrive\GitHub\FinTwit_Bot\src\cogs\loops\timeline.py", line 127, in get_latest_tweet
    tweets = await get_tweet()
  File "C:\Users\super\OneDrive\GitHub\FinTwit_Bot\src\util\get_tweet.py", line 55, in get_tweet
    tweet = result["data"]["home"]["home_timeline_urt"]["instructions"][0][
KeyError: 'entries'

**Comment by StephanAkkerman** [comment]
catching error now, still unclear why it happens

**Comment by StephanAkkerman** [comment]
Does not seem to happen anymore??
